version: '2'
services:
    movie-postgres:
        image: postgres:9.6
        environment:
            - POSTGRES_USER=movie
            - POSTGRES_PASSWORD=movie
            - POSTGRES_DB=movie
        networks:
            - network

    flyway:
        build:
            context: .
            dockerfile: Dockerfile-flyway
        image: flyway
        volumes:
            - ${PROJECT_HOME}/config/flyway.conf:/flyway/conf/flyway.conf
            - ${PROJECT_HOME}/migrations:/flyway/sql
        command: info migrate
        networks:
            - network

networks:
    network:
        driver: bridge
