version: '2'
services:
    redis:
        image: 'redis:3.2.7'

    postgres:
        image: postgres:9.6
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow

    webserver:
        build:
            context: .
            dockerfile: Dockerfile-airflow
        image: movie-docker-airflow
        restart: always
        depends_on:
            - postgres
            - redis
        environment:
            - LOAD_EX=n
            - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
            - EXECUTOR=Celery
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
        volumes:
            - $PWD/../dags:/usr/local/airflow/dags/
            - $PWD/../lib:/usr/local/airflow/lib/
        ports:
            - "8080:8080"
        command: webserver

    flower:
        build:
            context: .
            dockerfile: Dockerfile-airflow
        image: movie-docker-airflow
        restart: always
        depends_on:
            - redis
        environment:
            - EXECUTOR=Celery
        ports:
            - "5555:5555"
        command: flower

    scheduler:
        build:
            context: .
            dockerfile: Dockerfile-airflow
        image: movie-docker-airflow
        restart: always
        depends_on:
            - webserver
        volumes:
             - $PWD/../dags:/usr/local/airflow/dags/
             - $PWD/../lib:/usr/local/airflow/lib/
        environment:
            - LOAD_EX=n
            - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
            - EXECUTOR=Celery
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
        command: scheduler

    worker:
        build:
            context: .
            dockerfile: Dockerfile-airflow
        image: movie-docker-airflow
        restart: always
        depends_on:
            - scheduler
        volumes:
            - $PWD/../dags:/usr/local/airflow/dags/
            - $PWD/../lib:/usr/local/airflow/lib/
        environment:
            - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
            - EXECUTOR=Celery
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
        command: worker

volumes:
    data-volume:
