version: '2'
services:
    redis:
        image: 'redis:3.2.7'
        networks:
            - airflow-network

    postgres:
        image: postgres:9.6
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
        networks:
            - airflow-network

    webserver:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                HOST_AIRFLOW_HOME: ${AIRFLOW_HOME}
        image: movie-docker-airflow
        restart: always
        depends_on:
            - postgres
            - redis
        environment:
            - LOAD_EX=n
            - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
            - EXECUTOR=Celery
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
        volumes:
            - ${AIRFLOW_HOME}/dags:/usr/local/airflow/dags/
            - ${AIRFLOW_HOME}/lib:/usr/local/airflow/lib/
        ports:
            - "8080:8080"
        command: webserver
        networks:
            - airflow-network

    flower:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                HOST_AIRFLOW_HOME: ${AIRFLOW_HOME}
        image: movie-docker-airflow
        restart: always
        depends_on:
            - redis
        environment:
            - EXECUTOR=Celery
        ports:
            - "5555:5555"
        command: flower
        networks:
            - airflow-network

    scheduler:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                HOST_AIRFLOW_HOME: ${AIRFLOW_HOME}
        image: movie-docker-airflow
        restart: always
        depends_on:
            - webserver
        volumes:
            - ${AIRFLOW_HOME}/dags:/usr/local/airflow/dags/
            - ${AIRFLOW_HOME}/lib:/usr/local/airflow/lib/
        environment:
            - LOAD_EX=n
            - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
            - EXECUTOR=Celery
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
        command: scheduler
        networks:
            - airflow-network

    worker:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                HOST_AIRFLOW_HOME: ${AIRFLOW_HOME}
        image: movie-docker-airflow
        restart: always
        depends_on:
            - scheduler
        volumes:
            - ${AIRFLOW_HOME}/dags:/usr/local/airflow/dags/
            - ${AIRFLOW_HOME}/lib:/usr/local/airflow/lib/
        environment:
            - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
            - EXECUTOR=Celery
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
        command: worker
        networks:
            - airflow-network

networks:
    airflow-network:
        driver: bridge
