version: '2'
services:
    movie-postgres:
        image: postgres:9.6
        environment:
            - POSTGRES_USER=movie
            - POSTGRES_PASSWORD=movie
            - POSTGRES_DB=movie
        networks:
            - airflow-network

    flyway:
        image: shouldbee/flyway
        volumes:
            - ${AIRFLOW_HOME}/db/sql:/flyway/sql

networks:
    airflow-network:
        driver: bridge
